---
- name: install the iis web service
  hosts: windows

  tasks:
    - name: stop iis service
      win_service:
        name: W3Svc
        state: stopped
    
    - name: stop iis service
      win_feature:
        name: Web-Server
        state: absent

    - name: Create website index.html
      win_copy:
        content: "{{ iis_test_message }}"
        dest: C:\Inetpub\wwwroot\index.html
    
    - name: Show website address
      debug:
        msg: "http://{{ ansible_host }}"