---
- name: Install and configure AD authentication
  hosts: all
  gather_facts: no
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Install the required packages
      apt:
        name: ['krb5-user', 'samba', 'sssd', 'sssd-tools', 'libnss-sss', 'libpam-sss', 'ntp', 'ntpdate', 'realmd', 'adcli']
        state: present
      notify:
        - restart realmd

    - name: Install pexpect using pip
      pip:
        name: pexpect
        

    - name: Add mds5 to hosts file
      lineinfile:
        path: /etc/hosts
        line: '146.95.1.52  mds5.hunter.local mds5'
        backup: yes
      
    - name: Add DNS to nameserver
      lineinfile:
        path: /etc/resolv.conf
        line: '{{ item }}'
        backup: yes
      with_items: 
          - 'nameserver 146.95.1.12'
          - 'nameserver 146.95.1.17'
      
    - name: Join system to AD and add the computer object in the Linux OU
      shell: |
        echo bind_password | realm join –-user=tk912	HUNTER.LOCAL
        realm permit -g cstest
        realm list
      register: results
    
    - name: See the results
      debug:
        msg: "{{ results }}"

    - name: Add default_domain_suffix to sssd.conf
      lineinfile:
        dest: /etc/sssd/sssd.conf
        line: 'default_domain_suffix = hunter.local'
        insertafter: '^\[sssd\]'
      notify:
        - restart sssd

    - name: Allow the cstest group to logon to the system
      command: /bin/bash -c "/usr/sbin/realm permit -g cstest"

  handlers:
    - name: restart realmd
      service:
        name: realmd
        state: restarted

    - name: restart sssd
      service:
        name: sssd
        state: restarted
