---
- hosts: all
  name: Install Pip
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Install Pip
    - easy install: 
        name: pip
        state: latest
      become_user: root
