---
- hosts: all
  name: Install Pip
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
      become_user: root
    - name: Create app folder
      file:
        name: /opt/pythonapp
        state: directory
        recurse: yes
    - name: Install virtualenv module
      pip:
        name: virtualenv
        state: latest
        executable: pip3
