---
- hosts: all
  name: Update Machine
  become: True
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: update and upgrade all apps
      apt:
        name: "*"
        state: latest
        force_apt_get: yes
        update_cache: yes
        cache_valid_time: 3600
        
      
  
