---
- hosts: all
  name: Update Machine
  become: true
  
  tasks:
    - name: update and upgrade all apps
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
        
      
  
