---
- hosts: all
  name: Update Machine
  
  tasks:
    - name: update and upgrade all apps
      become: true
      become_method: sudo
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
        
      
  
